name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Check for updates
        run: |
          npm outdated || true
          
      - name: Update dependencies
        run: npm update
        
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: |
          npm run test
          npm run test:e2e
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: '⬆️ Update dependencies'
          body: |
            This PR updates project dependencies to their latest versions.
            
            Changes:
            - Updated npm dependencies
            
            This PR was automatically created by the Dependencies workflow.
          branch: update-dependencies
          delete-branch: true
          labels: dependencies
